package com.jd.blockchain.contract.archiver;

import java.io.File;

/**
 * The archive generated by {@link ContractArchiver};
 * 
 * @author huanghaiquan
 *
 */
public interface Archive {
	
	String getType();
	
	ArchiveLayout getLayout();
	
	File getFile();
	
}
